require("plugins.setup")


require("plugins.autopairs")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
-- require("plugins.gitsigns")
require("plugins.nvim-cmp")
require("plugins.nvim-treesitter")
require("plugins.catppuccin-theme")
require("plugins.nvim-surround")
require("plugins.indent")
require("plugins.context")
require("plugins.default")
require("plugins.neodev")
require("plugins.keybinds")
require("plugins.dap")
