accent: "#7aa2f7"
shell: /usr/bin/bash
start_dir: /home/sveinn/code
scrollback_lines: 10000
select_copy: true
bar_position: top

terminal_envs:
  TERM: xterm-256color

commands:
  ctrl+l: lazygit
  ctrl+h: htop

keybindings:
  session-manager: alt+o
  tab-manager: alt+p
  split-horizontal: alt+n
  split-vertical: ctrl+n
  focus-left: alt+h
  focus-right: alt+l
  focus-up: alt+k
  focus-down: alt+j
  detach: alt+\
  fullscreen: alt+m
  terminal-settings: alt+s

sessions:
  1: { name: ec, key: F1 }
  2: { name: eos, key: F2 }
  3: { name: tunnels, key: F3 }
  4: { name: crypto, key: F4 }
  5: { name: rmux, key: F5 }
  6: { name: sssh, key: F6 }
  7: { name: xls, key: F7 }
