theme = "keyb1nd"

[keys.normal]
"S-m" = ["vsplit", "goto_definition"]
"C-k" = "half_page_up"
"C-j" = "half_page_down"

"S-l" = "jump_view_right"
"S-j" = "jump_view_down"
"S-k" = "jump_view_up"
"S-h" = "jump_view_left"

[editor]
line-number = "relative"
soft-wrap.enable = true
end-of-line-diagnostics = "hint" 

[editor.inline-diagnostics] 
cursor-line = "error"

[editor.file-picker]
hidden = false
